version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: etl-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: etl_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  etl-app:
    build: .
    container_name: etl-app
    restart: always
    depends_on:
      - postgres
    environment:
      DB_HOST: localhost
      DB_USER: postgres_user
      DB_PASSWORD: postgres_password
      DB_NAME: etl_db
    volumes:
      - ./data/raw:/app/data/raw
      - ./data/processed:/app/data/processed
      - ./logs:/app/logs
    ports:
      - "8080:8080"

volumes:
  postgres_data:
